### ISSUE TITLE
Turning off the debug logger

### ISSUE THREAD

**Issue by bcardarella** [appcues/mojito#25]
Can the debug logger be turned off? The responses are flooding my console

**Comment by gamache** [comment]
Fixed in 0.4.0.

**Comment by heyitsjames** [comment]
I'm still seeing the debug output in my console (using `.0.6.1`). Anything I can do about this?

**Comment by bcardarella** [comment]
The debugs are now coming from Mint. I honestly don't understand why they're being used considering how incredibly noisy they are. I haven't yet advocated to turn them off in Mint yet but you can temporarily turn them off with `Logger.configure(level: :info)`
